databases:
  - name: firstapi
    databaseName: firstapi
    user: luluoliv

services:
  - type: web
    name: firstapi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn firstapi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: firstapi
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4